// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: services/v1/diseas_sensor.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	DiseasSensorService_DiseasSensorCreate_FullMethodName = "/services.v1.DiseasSensorService/DiseasSensorCreate"
	DiseasSensorService_DiseasSensorGet_FullMethodName    = "/services.v1.DiseasSensorService/DiseasSensorGet"
)

// DiseasSensorServiceClient is the client API for DiseasSensorService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiseasSensorServiceClient interface {
	DiseasSensorCreate(ctx context.Context, in *DiseasSensorCreateRequest, opts ...grpc.CallOption) (*DiseasSensorCreateReply, error)
	DiseasSensorGet(ctx context.Context, in *DiseasSensorGetRequest, opts ...grpc.CallOption) (*DiseasSensorGetReply, error)
}

type diseasSensorServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDiseasSensorServiceClient(cc grpc.ClientConnInterface) DiseasSensorServiceClient {
	return &diseasSensorServiceClient{cc}
}

func (c *diseasSensorServiceClient) DiseasSensorCreate(ctx context.Context, in *DiseasSensorCreateRequest, opts ...grpc.CallOption) (*DiseasSensorCreateReply, error) {
	out := new(DiseasSensorCreateReply)
	err := c.cc.Invoke(ctx, DiseasSensorService_DiseasSensorCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *diseasSensorServiceClient) DiseasSensorGet(ctx context.Context, in *DiseasSensorGetRequest, opts ...grpc.CallOption) (*DiseasSensorGetReply, error) {
	out := new(DiseasSensorGetReply)
	err := c.cc.Invoke(ctx, DiseasSensorService_DiseasSensorGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiseasSensorServiceServer is the server API for DiseasSensorService service.
// All implementations should embed UnimplementedDiseasSensorServiceServer
// for forward compatibility
type DiseasSensorServiceServer interface {
	DiseasSensorCreate(context.Context, *DiseasSensorCreateRequest) (*DiseasSensorCreateReply, error)
	DiseasSensorGet(context.Context, *DiseasSensorGetRequest) (*DiseasSensorGetReply, error)
}

// UnimplementedDiseasSensorServiceServer should be embedded to have forward compatible implementations.
type UnimplementedDiseasSensorServiceServer struct {
}

func (UnimplementedDiseasSensorServiceServer) DiseasSensorCreate(context.Context, *DiseasSensorCreateRequest) (*DiseasSensorCreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiseasSensorCreate not implemented")
}
func (UnimplementedDiseasSensorServiceServer) DiseasSensorGet(context.Context, *DiseasSensorGetRequest) (*DiseasSensorGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DiseasSensorGet not implemented")
}

// UnsafeDiseasSensorServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiseasSensorServiceServer will
// result in compilation errors.
type UnsafeDiseasSensorServiceServer interface {
	mustEmbedUnimplementedDiseasSensorServiceServer()
}

func RegisterDiseasSensorServiceServer(s grpc.ServiceRegistrar, srv DiseasSensorServiceServer) {
	s.RegisterService(&DiseasSensorService_ServiceDesc, srv)
}

func _DiseasSensorService_DiseasSensorCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiseasSensorCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiseasSensorServiceServer).DiseasSensorCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiseasSensorService_DiseasSensorCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiseasSensorServiceServer).DiseasSensorCreate(ctx, req.(*DiseasSensorCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DiseasSensorService_DiseasSensorGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiseasSensorGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiseasSensorServiceServer).DiseasSensorGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DiseasSensorService_DiseasSensorGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiseasSensorServiceServer).DiseasSensorGet(ctx, req.(*DiseasSensorGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DiseasSensorService_ServiceDesc is the grpc.ServiceDesc for DiseasSensorService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DiseasSensorService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.v1.DiseasSensorService",
	HandlerType: (*DiseasSensorServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DiseasSensorCreate",
			Handler:    _DiseasSensorService_DiseasSensorCreate_Handler,
		},
		{
			MethodName: "DiseasSensorGet",
			Handler:    _DiseasSensorService_DiseasSensorGet_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/v1/diseas_sensor.proto",
}
