// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: services/v1/diseas.proto

package v1

import (
	v1 "github.com/MediStatTech/biometric-client/pb/go/models/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// =====================
// DiseasCreate
// =====================
type DiseasCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Diseas *v1.Diseas_Create `protobuf:"bytes,1,opt,name=diseas,proto3" json:"diseas,omitempty"`
}

func (x *DiseasCreateRequest) Reset() {
	*x = DiseasCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_diseas_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiseasCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiseasCreateRequest) ProtoMessage() {}

func (x *DiseasCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_diseas_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiseasCreateRequest.ProtoReflect.Descriptor instead.
func (*DiseasCreateRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_diseas_proto_rawDescGZIP(), []int{0}
}

func (x *DiseasCreateRequest) GetDiseas() *v1.Diseas_Create {
	if x != nil {
		return x.Diseas
	}
	return nil
}

type DiseasCreateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Diseas *v1.Diseas_Read `protobuf:"bytes,1,opt,name=diseas,proto3" json:"diseas,omitempty"`
}

func (x *DiseasCreateReply) Reset() {
	*x = DiseasCreateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_diseas_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiseasCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiseasCreateReply) ProtoMessage() {}

func (x *DiseasCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_diseas_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiseasCreateReply.ProtoReflect.Descriptor instead.
func (*DiseasCreateReply) Descriptor() ([]byte, []int) {
	return file_services_v1_diseas_proto_rawDescGZIP(), []int{1}
}

func (x *DiseasCreateReply) GetDiseas() *v1.Diseas_Read {
	if x != nil {
		return x.Diseas
	}
	return nil
}

// =====================
// DiseasGet
// =====================
type DiseasGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DiseasGetRequest) Reset() {
	*x = DiseasGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_diseas_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiseasGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiseasGetRequest) ProtoMessage() {}

func (x *DiseasGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_diseas_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiseasGetRequest.ProtoReflect.Descriptor instead.
func (*DiseasGetRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_diseas_proto_rawDescGZIP(), []int{2}
}

type DiseasGetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Diseases []*v1.Diseas_Read `protobuf:"bytes,1,rep,name=diseases,proto3" json:"diseases,omitempty"`
}

func (x *DiseasGetReply) Reset() {
	*x = DiseasGetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_diseas_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiseasGetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiseasGetReply) ProtoMessage() {}

func (x *DiseasGetReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_diseas_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiseasGetReply.ProtoReflect.Descriptor instead.
func (*DiseasGetReply) Descriptor() ([]byte, []int) {
	return file_services_v1_diseas_proto_rawDescGZIP(), []int{3}
}

func (x *DiseasGetReply) GetDiseases() []*v1.Diseas_Read {
	if x != nil {
		return x.Diseases
	}
	return nil
}

var File_services_v1_diseas_proto protoreflect.FileDescriptor

var file_services_v1_diseas_proto_rawDesc = []byte{
	0x0a, 0x18, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69,
	0x73, 0x65, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x16, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f,
	0x76, 0x31, 0x2f, 0x64, 0x69, 0x73, 0x65, 0x61, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x47, 0x0a, 0x13, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x30, 0x0a, 0x06, 0x64, 0x69, 0x73, 0x65, 0x61, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x06, 0x64, 0x69, 0x73, 0x65, 0x61, 0x73, 0x22, 0x43, 0x0a, 0x11, 0x44, 0x69, 0x73, 0x65,
	0x61, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x2e, 0x0a,
	0x06, 0x64, 0x69, 0x73, 0x65, 0x61, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x06, 0x64, 0x69, 0x73, 0x65, 0x61, 0x73, 0x22, 0x12, 0x0a,
	0x10, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x22, 0x44, 0x0a, 0x0e, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x32, 0x0a, 0x08, 0x64, 0x69, 0x73, 0x65, 0x61, 0x73, 0x65, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x08, 0x64,
	0x69, 0x73, 0x65, 0x61, 0x73, 0x65, 0x73, 0x32, 0xb0, 0x01, 0x0a, 0x0d, 0x44, 0x69, 0x73, 0x65,
	0x61, 0x73, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x50, 0x0a, 0x0c, 0x44, 0x69, 0x73,
	0x65, 0x61, 0x73, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x20, 0x2e, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x4d, 0x0a, 0x09, 0x44,
	0x69, 0x73, 0x65, 0x61, 0x73, 0x47, 0x65, 0x74, 0x12, 0x20, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x65, 0x64, 0x69, 0x53, 0x74, 0x61,
	0x74, 0x54, 0x65, 0x63, 0x68, 0x2f, 0x62, 0x69, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2d,
	0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_v1_diseas_proto_rawDescOnce sync.Once
	file_services_v1_diseas_proto_rawDescData = file_services_v1_diseas_proto_rawDesc
)

func file_services_v1_diseas_proto_rawDescGZIP() []byte {
	file_services_v1_diseas_proto_rawDescOnce.Do(func() {
		file_services_v1_diseas_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_v1_diseas_proto_rawDescData)
	})
	return file_services_v1_diseas_proto_rawDescData
}

var file_services_v1_diseas_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_v1_diseas_proto_goTypes = []interface{}{
	(*DiseasCreateRequest)(nil), // 0: services.v1.DiseasCreateRequest
	(*DiseasCreateReply)(nil),   // 1: services.v1.DiseasCreateReply
	(*DiseasGetRequest)(nil),    // 2: services.v1.DiseasGetRequest
	(*DiseasGetReply)(nil),      // 3: services.v1.DiseasGetReply
	(*v1.Diseas_Create)(nil),    // 4: models.v1.Diseas.Create
	(*v1.Diseas_Read)(nil),      // 5: models.v1.Diseas.Read
}
var file_services_v1_diseas_proto_depIdxs = []int32{
	4, // 0: services.v1.DiseasCreateRequest.diseas:type_name -> models.v1.Diseas.Create
	5, // 1: services.v1.DiseasCreateReply.diseas:type_name -> models.v1.Diseas.Read
	5, // 2: services.v1.DiseasGetReply.diseases:type_name -> models.v1.Diseas.Read
	0, // 3: services.v1.DiseasService.DiseasCreate:input_type -> services.v1.DiseasCreateRequest
	0, // 4: services.v1.DiseasService.DiseasGet:input_type -> services.v1.DiseasCreateRequest
	1, // 5: services.v1.DiseasService.DiseasCreate:output_type -> services.v1.DiseasCreateReply
	1, // 6: services.v1.DiseasService.DiseasGet:output_type -> services.v1.DiseasCreateReply
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_services_v1_diseas_proto_init() }
func file_services_v1_diseas_proto_init() {
	if File_services_v1_diseas_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_v1_diseas_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiseasCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_diseas_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiseasCreateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_diseas_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiseasGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_diseas_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiseasGetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_v1_diseas_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_v1_diseas_proto_goTypes,
		DependencyIndexes: file_services_v1_diseas_proto_depIdxs,
		MessageInfos:      file_services_v1_diseas_proto_msgTypes,
	}.Build()
	File_services_v1_diseas_proto = out.File
	file_services_v1_diseas_proto_rawDesc = nil
	file_services_v1_diseas_proto_goTypes = nil
	file_services_v1_diseas_proto_depIdxs = nil
}
