// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: services/v1/diseas_sensor.proto

package v1

import (
	v1 "github.com/MediStatTech/biometric-client/pb/go/models/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// =====================
// DiseasSensorCreate
// =====================
type DiseasSensorCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiseasSensor *v1.DiseasSensor_Create `protobuf:"bytes,1,opt,name=diseas_sensor,json=diseasSensor,proto3" json:"diseas_sensor,omitempty"`
}

func (x *DiseasSensorCreateRequest) Reset() {
	*x = DiseasSensorCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_diseas_sensor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiseasSensorCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiseasSensorCreateRequest) ProtoMessage() {}

func (x *DiseasSensorCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_diseas_sensor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiseasSensorCreateRequest.ProtoReflect.Descriptor instead.
func (*DiseasSensorCreateRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_diseas_sensor_proto_rawDescGZIP(), []int{0}
}

func (x *DiseasSensorCreateRequest) GetDiseasSensor() *v1.DiseasSensor_Create {
	if x != nil {
		return x.DiseasSensor
	}
	return nil
}

type DiseasSensorCreateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiseasSensor *v1.DiseasSensor_Read `protobuf:"bytes,1,opt,name=diseas_sensor,json=diseasSensor,proto3" json:"diseas_sensor,omitempty"`
}

func (x *DiseasSensorCreateReply) Reset() {
	*x = DiseasSensorCreateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_diseas_sensor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiseasSensorCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiseasSensorCreateReply) ProtoMessage() {}

func (x *DiseasSensorCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_diseas_sensor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiseasSensorCreateReply.ProtoReflect.Descriptor instead.
func (*DiseasSensorCreateReply) Descriptor() ([]byte, []int) {
	return file_services_v1_diseas_sensor_proto_rawDescGZIP(), []int{1}
}

func (x *DiseasSensorCreateReply) GetDiseasSensor() *v1.DiseasSensor_Read {
	if x != nil {
		return x.DiseasSensor
	}
	return nil
}

// =====================
// DiseasSensorGet
// =====================
type DiseasSensorGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiseasId string `protobuf:"bytes,1,opt,name=diseas_id,json=diseasId,proto3" json:"diseas_id,omitempty"`
}

func (x *DiseasSensorGetRequest) Reset() {
	*x = DiseasSensorGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_diseas_sensor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiseasSensorGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiseasSensorGetRequest) ProtoMessage() {}

func (x *DiseasSensorGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_diseas_sensor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiseasSensorGetRequest.ProtoReflect.Descriptor instead.
func (*DiseasSensorGetRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_diseas_sensor_proto_rawDescGZIP(), []int{2}
}

func (x *DiseasSensorGetRequest) GetDiseasId() string {
	if x != nil {
		return x.DiseasId
	}
	return ""
}

type DiseasSensorGetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiseasSensors []*v1.DiseasSensor_Read `protobuf:"bytes,1,rep,name=diseas_sensors,json=diseasSensors,proto3" json:"diseas_sensors,omitempty"`
}

func (x *DiseasSensorGetReply) Reset() {
	*x = DiseasSensorGetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_diseas_sensor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiseasSensorGetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiseasSensorGetReply) ProtoMessage() {}

func (x *DiseasSensorGetReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_diseas_sensor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiseasSensorGetReply.ProtoReflect.Descriptor instead.
func (*DiseasSensorGetReply) Descriptor() ([]byte, []int) {
	return file_services_v1_diseas_sensor_proto_rawDescGZIP(), []int{3}
}

func (x *DiseasSensorGetReply) GetDiseasSensors() []*v1.DiseasSensor_Read {
	if x != nil {
		return x.DiseasSensors
	}
	return nil
}

var File_services_v1_diseas_sensor_proto protoreflect.FileDescriptor

var file_services_v1_diseas_sensor_proto_rawDesc = []byte{
	0x0a, 0x1f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69,
	0x73, 0x65, 0x61, 0x73, 0x5f, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1d,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69, 0x73, 0x65, 0x61, 0x73,
	0x5f, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x60, 0x0a,
	0x19, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x0d, 0x64, 0x69,
	0x73, 0x65, 0x61, 0x73, 0x5f, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1e, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69,
	0x73, 0x65, 0x61, 0x73, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x52, 0x0c, 0x64, 0x69, 0x73, 0x65, 0x61, 0x73, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x22,
	0x5c, 0x0a, 0x17, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x41, 0x0a, 0x0d, 0x64, 0x69,
	0x73, 0x65, 0x61, 0x73, 0x5f, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69,
	0x73, 0x65, 0x61, 0x73, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52,
	0x0c, 0x64, 0x69, 0x73, 0x65, 0x61, 0x73, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x22, 0x35, 0x0a,
	0x16, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x65, 0x61,
	0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x65,
	0x61, 0x73, 0x49, 0x64, 0x22, 0x5b, 0x0a, 0x14, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73, 0x53, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x43, 0x0a, 0x0e,
	0x64, 0x69, 0x73, 0x65, 0x61, 0x73, 0x5f, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31,
	0x2e, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x2e, 0x52, 0x65,
	0x61, 0x64, 0x52, 0x0d, 0x64, 0x69, 0x73, 0x65, 0x61, 0x73, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x73, 0x32, 0xd4, 0x01, 0x0a, 0x13, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73, 0x53, 0x65, 0x6e, 0x73,
	0x6f, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x62, 0x0a, 0x12, 0x44, 0x69, 0x73,
	0x65, 0x61, 0x73, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12,
	0x26, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69,
	0x73, 0x65, 0x61, 0x73, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73, 0x53, 0x65, 0x6e, 0x73,
	0x6f, 0x72, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x59, 0x0a,
	0x0f, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x47, 0x65, 0x74,
	0x12, 0x23, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x44,
	0x69, 0x73, 0x65, 0x61, 0x73, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x65, 0x61, 0x73, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x65, 0x64, 0x69, 0x53, 0x74, 0x61, 0x74, 0x54,
	0x65, 0x63, 0x68, 0x2f, 0x62, 0x69, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2d, 0x63, 0x6c,
	0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_v1_diseas_sensor_proto_rawDescOnce sync.Once
	file_services_v1_diseas_sensor_proto_rawDescData = file_services_v1_diseas_sensor_proto_rawDesc
)

func file_services_v1_diseas_sensor_proto_rawDescGZIP() []byte {
	file_services_v1_diseas_sensor_proto_rawDescOnce.Do(func() {
		file_services_v1_diseas_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_v1_diseas_sensor_proto_rawDescData)
	})
	return file_services_v1_diseas_sensor_proto_rawDescData
}

var file_services_v1_diseas_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_v1_diseas_sensor_proto_goTypes = []interface{}{
	(*DiseasSensorCreateRequest)(nil), // 0: services.v1.DiseasSensorCreateRequest
	(*DiseasSensorCreateReply)(nil),   // 1: services.v1.DiseasSensorCreateReply
	(*DiseasSensorGetRequest)(nil),    // 2: services.v1.DiseasSensorGetRequest
	(*DiseasSensorGetReply)(nil),      // 3: services.v1.DiseasSensorGetReply
	(*v1.DiseasSensor_Create)(nil),    // 4: models.v1.DiseasSensor.Create
	(*v1.DiseasSensor_Read)(nil),      // 5: models.v1.DiseasSensor.Read
}
var file_services_v1_diseas_sensor_proto_depIdxs = []int32{
	4, // 0: services.v1.DiseasSensorCreateRequest.diseas_sensor:type_name -> models.v1.DiseasSensor.Create
	5, // 1: services.v1.DiseasSensorCreateReply.diseas_sensor:type_name -> models.v1.DiseasSensor.Read
	5, // 2: services.v1.DiseasSensorGetReply.diseas_sensors:type_name -> models.v1.DiseasSensor.Read
	0, // 3: services.v1.DiseasSensorService.DiseasSensorCreate:input_type -> services.v1.DiseasSensorCreateRequest
	2, // 4: services.v1.DiseasSensorService.DiseasSensorGet:input_type -> services.v1.DiseasSensorGetRequest
	1, // 5: services.v1.DiseasSensorService.DiseasSensorCreate:output_type -> services.v1.DiseasSensorCreateReply
	3, // 6: services.v1.DiseasSensorService.DiseasSensorGet:output_type -> services.v1.DiseasSensorGetReply
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_services_v1_diseas_sensor_proto_init() }
func file_services_v1_diseas_sensor_proto_init() {
	if File_services_v1_diseas_sensor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_v1_diseas_sensor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiseasSensorCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_diseas_sensor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiseasSensorCreateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_diseas_sensor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiseasSensorGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_diseas_sensor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiseasSensorGetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_v1_diseas_sensor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_v1_diseas_sensor_proto_goTypes,
		DependencyIndexes: file_services_v1_diseas_sensor_proto_depIdxs,
		MessageInfos:      file_services_v1_diseas_sensor_proto_msgTypes,
	}.Build()
	File_services_v1_diseas_sensor_proto = out.File
	file_services_v1_diseas_sensor_proto_rawDesc = nil
	file_services_v1_diseas_sensor_proto_goTypes = nil
	file_services_v1_diseas_sensor_proto_depIdxs = nil
}
