// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: services/v1/metric_type.proto

package v1

import (
	v1 "github.com/MediStatTech/biometric-client/pb/go/models/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MetricTypeCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SensorId   string                `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	MetricType *v1.MetricType_Create `protobuf:"bytes,2,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
}

func (x *MetricTypeCreateRequest) Reset() {
	*x = MetricTypeCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_metric_type_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricTypeCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricTypeCreateRequest) ProtoMessage() {}

func (x *MetricTypeCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_metric_type_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricTypeCreateRequest.ProtoReflect.Descriptor instead.
func (*MetricTypeCreateRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_metric_type_proto_rawDescGZIP(), []int{0}
}

func (x *MetricTypeCreateRequest) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *MetricTypeCreateRequest) GetMetricType() *v1.MetricType_Create {
	if x != nil {
		return x.MetricType
	}
	return nil
}

type MetricTypeCreateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetricType *v1.MetricType_Read `protobuf:"bytes,1,opt,name=metric_type,json=metricType,proto3" json:"metric_type,omitempty"`
}

func (x *MetricTypeCreateReply) Reset() {
	*x = MetricTypeCreateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_metric_type_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricTypeCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricTypeCreateReply) ProtoMessage() {}

func (x *MetricTypeCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_metric_type_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricTypeCreateReply.ProtoReflect.Descriptor instead.
func (*MetricTypeCreateReply) Descriptor() ([]byte, []int) {
	return file_services_v1_metric_type_proto_rawDescGZIP(), []int{1}
}

func (x *MetricTypeCreateReply) GetMetricType() *v1.MetricType_Read {
	if x != nil {
		return x.MetricType
	}
	return nil
}

type MetricTypeGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SensorId string `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
}

func (x *MetricTypeGetRequest) Reset() {
	*x = MetricTypeGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_metric_type_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricTypeGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricTypeGetRequest) ProtoMessage() {}

func (x *MetricTypeGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_metric_type_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricTypeGetRequest.ProtoReflect.Descriptor instead.
func (*MetricTypeGetRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_metric_type_proto_rawDescGZIP(), []int{2}
}

func (x *MetricTypeGetRequest) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

type MetricTypeGetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MetricTypes []*v1.MetricType_Read `protobuf:"bytes,1,rep,name=metric_types,json=metricTypes,proto3" json:"metric_types,omitempty"`
}

func (x *MetricTypeGetReply) Reset() {
	*x = MetricTypeGetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_metric_type_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MetricTypeGetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricTypeGetReply) ProtoMessage() {}

func (x *MetricTypeGetReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_metric_type_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricTypeGetReply.ProtoReflect.Descriptor instead.
func (*MetricTypeGetReply) Descriptor() ([]byte, []int) {
	return file_services_v1_metric_type_proto_rawDescGZIP(), []int{3}
}

func (x *MetricTypeGetReply) GetMetricTypes() []*v1.MetricType_Read {
	if x != nil {
		return x.MetricTypes
	}
	return nil
}

var File_services_v1_metric_type_proto protoreflect.FileDescriptor

var file_services_v1_metric_type_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x1a, 0x1b, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x75, 0x0a, 0x17, 0x4d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x49,
	0x64, 0x12, 0x3d, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65,
	0x22, 0x54, 0x0a, 0x15, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x3b, 0x0a, 0x0b, 0x6d, 0x65, 0x74,
	0x72, 0x69, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a,
	0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69,
	0x63, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x0a, 0x6d, 0x65, 0x74, 0x72,
	0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x22, 0x33, 0x0a, 0x14, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x54, 0x79, 0x70, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b,
	0x0a, 0x09, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x53, 0x0a, 0x12, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x12, 0x3d, 0x0a, 0x0c, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x5f, 0x74, 0x79, 0x70, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x52,
	0x65, 0x61, 0x64, 0x52, 0x0b, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x73,
	0x32, 0xc6, 0x01, 0x0a, 0x11, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5c, 0x0a, 0x10, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63,
	0x54, 0x79, 0x70, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x24, 0x2e, 0x73, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x54,
	0x79, 0x70, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x22, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4d,
	0x65, 0x74, 0x72, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x53, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x54, 0x79,
	0x70, 0x65, 0x47, 0x65, 0x74, 0x12, 0x21, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x54, 0x79, 0x70, 0x65, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1f, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x4d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x54, 0x79, 0x70,
	0x65, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x65, 0x64, 0x69, 0x53, 0x74, 0x61, 0x74,
	0x54, 0x65, 0x63, 0x68, 0x2f, 0x62, 0x69, 0x6f, 0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2d, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x62, 0x2f, 0x67, 0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_v1_metric_type_proto_rawDescOnce sync.Once
	file_services_v1_metric_type_proto_rawDescData = file_services_v1_metric_type_proto_rawDesc
)

func file_services_v1_metric_type_proto_rawDescGZIP() []byte {
	file_services_v1_metric_type_proto_rawDescOnce.Do(func() {
		file_services_v1_metric_type_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_v1_metric_type_proto_rawDescData)
	})
	return file_services_v1_metric_type_proto_rawDescData
}

var file_services_v1_metric_type_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_services_v1_metric_type_proto_goTypes = []interface{}{
	(*MetricTypeCreateRequest)(nil), // 0: services.v1.MetricTypeCreateRequest
	(*MetricTypeCreateReply)(nil),   // 1: services.v1.MetricTypeCreateReply
	(*MetricTypeGetRequest)(nil),    // 2: services.v1.MetricTypeGetRequest
	(*MetricTypeGetReply)(nil),      // 3: services.v1.MetricTypeGetReply
	(*v1.MetricType_Create)(nil),    // 4: models.v1.MetricType.Create
	(*v1.MetricType_Read)(nil),      // 5: models.v1.MetricType.Read
}
var file_services_v1_metric_type_proto_depIdxs = []int32{
	4, // 0: services.v1.MetricTypeCreateRequest.metric_type:type_name -> models.v1.MetricType.Create
	5, // 1: services.v1.MetricTypeCreateReply.metric_type:type_name -> models.v1.MetricType.Read
	5, // 2: services.v1.MetricTypeGetReply.metric_types:type_name -> models.v1.MetricType.Read
	0, // 3: services.v1.MetricTypeService.MetricTypeCreate:input_type -> services.v1.MetricTypeCreateRequest
	2, // 4: services.v1.MetricTypeService.MetricTypeGet:input_type -> services.v1.MetricTypeGetRequest
	1, // 5: services.v1.MetricTypeService.MetricTypeCreate:output_type -> services.v1.MetricTypeCreateReply
	3, // 6: services.v1.MetricTypeService.MetricTypeGet:output_type -> services.v1.MetricTypeGetReply
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_services_v1_metric_type_proto_init() }
func file_services_v1_metric_type_proto_init() {
	if File_services_v1_metric_type_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_v1_metric_type_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricTypeCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_metric_type_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricTypeCreateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_metric_type_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricTypeGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_metric_type_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MetricTypeGetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_v1_metric_type_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_v1_metric_type_proto_goTypes,
		DependencyIndexes: file_services_v1_metric_type_proto_depIdxs,
		MessageInfos:      file_services_v1_metric_type_proto_msgTypes,
	}.Build()
	File_services_v1_metric_type_proto = out.File
	file_services_v1_metric_type_proto_rawDesc = nil
	file_services_v1_metric_type_proto_goTypes = nil
	file_services_v1_metric_type_proto_depIdxs = nil
}
