// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: services/v1/patient_status.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	PatientStatusService_PatientStatusGetBatch_FullMethodName = "/services.v1.PatientStatusService/PatientStatusGetBatch"
)

// PatientStatusServiceClient is the client API for PatientStatusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PatientStatusServiceClient interface {
	PatientStatusGetBatch(ctx context.Context, in *PatientStatusGetBatchRequest, opts ...grpc.CallOption) (*PatientStatusGetBatchReply, error)
}

type patientStatusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPatientStatusServiceClient(cc grpc.ClientConnInterface) PatientStatusServiceClient {
	return &patientStatusServiceClient{cc}
}

func (c *patientStatusServiceClient) PatientStatusGetBatch(ctx context.Context, in *PatientStatusGetBatchRequest, opts ...grpc.CallOption) (*PatientStatusGetBatchReply, error) {
	out := new(PatientStatusGetBatchReply)
	err := c.cc.Invoke(ctx, PatientStatusService_PatientStatusGetBatch_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PatientStatusServiceServer is the server API for PatientStatusService service.
// All implementations should embed UnimplementedPatientStatusServiceServer
// for forward compatibility
type PatientStatusServiceServer interface {
	PatientStatusGetBatch(context.Context, *PatientStatusGetBatchRequest) (*PatientStatusGetBatchReply, error)
}

// UnimplementedPatientStatusServiceServer should be embedded to have forward compatible implementations.
type UnimplementedPatientStatusServiceServer struct {
}

func (UnimplementedPatientStatusServiceServer) PatientStatusGetBatch(context.Context, *PatientStatusGetBatchRequest) (*PatientStatusGetBatchReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PatientStatusGetBatch not implemented")
}

// UnsafePatientStatusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PatientStatusServiceServer will
// result in compilation errors.
type UnsafePatientStatusServiceServer interface {
	mustEmbedUnimplementedPatientStatusServiceServer()
}

func RegisterPatientStatusServiceServer(s grpc.ServiceRegistrar, srv PatientStatusServiceServer) {
	s.RegisterService(&PatientStatusService_ServiceDesc, srv)
}

func _PatientStatusService_PatientStatusGetBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PatientStatusGetBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PatientStatusServiceServer).PatientStatusGetBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PatientStatusService_PatientStatusGetBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PatientStatusServiceServer).PatientStatusGetBatch(ctx, req.(*PatientStatusGetBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PatientStatusService_ServiceDesc is the grpc.ServiceDesc for PatientStatusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PatientStatusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.v1.PatientStatusService",
	HandlerType: (*PatientStatusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PatientStatusGetBatch",
			Handler:    _PatientStatusService_PatientStatusGetBatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/v1/patient_status.proto",
}
