// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             (unknown)
// source: services/v1/sensor_patient.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	SensorPatientService_SensorPatientCreate_FullMethodName   = "/services.v1.SensorPatientService/SensorPatientCreate"
	SensorPatientService_SensorPatientGet_FullMethodName      = "/services.v1.SensorPatientService/SensorPatientGet"
	SensorPatientService_SensorPatientRetrieve_FullMethodName = "/services.v1.SensorPatientService/SensorPatientRetrieve"
)

// SensorPatientServiceClient is the client API for SensorPatientService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SensorPatientServiceClient interface {
	SensorPatientCreate(ctx context.Context, in *SensorPatientCreateRequest, opts ...grpc.CallOption) (*SensorPatientCreateReply, error)
	SensorPatientGet(ctx context.Context, in *SensorPatientGetRequest, opts ...grpc.CallOption) (*SensorPatientGetReply, error)
	SensorPatientRetrieve(ctx context.Context, in *SensorPatientRetrieveRequest, opts ...grpc.CallOption) (*SensorPatientRetrieveReply, error)
}

type sensorPatientServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSensorPatientServiceClient(cc grpc.ClientConnInterface) SensorPatientServiceClient {
	return &sensorPatientServiceClient{cc}
}

func (c *sensorPatientServiceClient) SensorPatientCreate(ctx context.Context, in *SensorPatientCreateRequest, opts ...grpc.CallOption) (*SensorPatientCreateReply, error) {
	out := new(SensorPatientCreateReply)
	err := c.cc.Invoke(ctx, SensorPatientService_SensorPatientCreate_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorPatientServiceClient) SensorPatientGet(ctx context.Context, in *SensorPatientGetRequest, opts ...grpc.CallOption) (*SensorPatientGetReply, error) {
	out := new(SensorPatientGetReply)
	err := c.cc.Invoke(ctx, SensorPatientService_SensorPatientGet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sensorPatientServiceClient) SensorPatientRetrieve(ctx context.Context, in *SensorPatientRetrieveRequest, opts ...grpc.CallOption) (*SensorPatientRetrieveReply, error) {
	out := new(SensorPatientRetrieveReply)
	err := c.cc.Invoke(ctx, SensorPatientService_SensorPatientRetrieve_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SensorPatientServiceServer is the server API for SensorPatientService service.
// All implementations should embed UnimplementedSensorPatientServiceServer
// for forward compatibility
type SensorPatientServiceServer interface {
	SensorPatientCreate(context.Context, *SensorPatientCreateRequest) (*SensorPatientCreateReply, error)
	SensorPatientGet(context.Context, *SensorPatientGetRequest) (*SensorPatientGetReply, error)
	SensorPatientRetrieve(context.Context, *SensorPatientRetrieveRequest) (*SensorPatientRetrieveReply, error)
}

// UnimplementedSensorPatientServiceServer should be embedded to have forward compatible implementations.
type UnimplementedSensorPatientServiceServer struct {
}

func (UnimplementedSensorPatientServiceServer) SensorPatientCreate(context.Context, *SensorPatientCreateRequest) (*SensorPatientCreateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SensorPatientCreate not implemented")
}
func (UnimplementedSensorPatientServiceServer) SensorPatientGet(context.Context, *SensorPatientGetRequest) (*SensorPatientGetReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SensorPatientGet not implemented")
}
func (UnimplementedSensorPatientServiceServer) SensorPatientRetrieve(context.Context, *SensorPatientRetrieveRequest) (*SensorPatientRetrieveReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SensorPatientRetrieve not implemented")
}

// UnsafeSensorPatientServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SensorPatientServiceServer will
// result in compilation errors.
type UnsafeSensorPatientServiceServer interface {
	mustEmbedUnimplementedSensorPatientServiceServer()
}

func RegisterSensorPatientServiceServer(s grpc.ServiceRegistrar, srv SensorPatientServiceServer) {
	s.RegisterService(&SensorPatientService_ServiceDesc, srv)
}

func _SensorPatientService_SensorPatientCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorPatientCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorPatientServiceServer).SensorPatientCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorPatientService_SensorPatientCreate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorPatientServiceServer).SensorPatientCreate(ctx, req.(*SensorPatientCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorPatientService_SensorPatientGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorPatientGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorPatientServiceServer).SensorPatientGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorPatientService_SensorPatientGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorPatientServiceServer).SensorPatientGet(ctx, req.(*SensorPatientGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SensorPatientService_SensorPatientRetrieve_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SensorPatientRetrieveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SensorPatientServiceServer).SensorPatientRetrieve(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SensorPatientService_SensorPatientRetrieve_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SensorPatientServiceServer).SensorPatientRetrieve(ctx, req.(*SensorPatientRetrieveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SensorPatientService_ServiceDesc is the grpc.ServiceDesc for SensorPatientService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SensorPatientService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "services.v1.SensorPatientService",
	HandlerType: (*SensorPatientServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SensorPatientCreate",
			Handler:    _SensorPatientService_SensorPatientCreate_Handler,
		},
		{
			MethodName: "SensorPatientGet",
			Handler:    _SensorPatientService_SensorPatientGet_Handler,
		},
		{
			MethodName: "SensorPatientRetrieve",
			Handler:    _SensorPatientService_SensorPatientRetrieve_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "services/v1/sensor_patient.proto",
}
