// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: services/v1/sensor_patient.proto

package v1

import (
	v1 "github.com/MediStatTech/biometric-client/pb/go/models/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// =====================
// SensorPatientCreate
// =====================
type SensorPatientCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PatientId string `protobuf:"bytes,1,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
	SensorId  string `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
}

func (x *SensorPatientCreateRequest) Reset() {
	*x = SensorPatientCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_sensor_patient_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SensorPatientCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorPatientCreateRequest) ProtoMessage() {}

func (x *SensorPatientCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_sensor_patient_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorPatientCreateRequest.ProtoReflect.Descriptor instead.
func (*SensorPatientCreateRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_sensor_patient_proto_rawDescGZIP(), []int{0}
}

func (x *SensorPatientCreateRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

func (x *SensorPatientCreateRequest) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

type SensorPatientCreateReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SensorPatient *v1.SensorPatient_Read `protobuf:"bytes,1,opt,name=sensor_patient,json=sensorPatient,proto3" json:"sensor_patient,omitempty"`
}

func (x *SensorPatientCreateReply) Reset() {
	*x = SensorPatientCreateReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_sensor_patient_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SensorPatientCreateReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorPatientCreateReply) ProtoMessage() {}

func (x *SensorPatientCreateReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_sensor_patient_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorPatientCreateReply.ProtoReflect.Descriptor instead.
func (*SensorPatientCreateReply) Descriptor() ([]byte, []int) {
	return file_services_v1_sensor_patient_proto_rawDescGZIP(), []int{1}
}

func (x *SensorPatientCreateReply) GetSensorPatient() *v1.SensorPatient_Read {
	if x != nil {
		return x.SensorPatient
	}
	return nil
}

// =====================
// SensorPatientGet
// =====================
type SensorPatientGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SensorId string `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
}

func (x *SensorPatientGetRequest) Reset() {
	*x = SensorPatientGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_sensor_patient_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SensorPatientGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorPatientGetRequest) ProtoMessage() {}

func (x *SensorPatientGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_sensor_patient_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorPatientGetRequest.ProtoReflect.Descriptor instead.
func (*SensorPatientGetRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_sensor_patient_proto_rawDescGZIP(), []int{2}
}

func (x *SensorPatientGetRequest) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

type SensorPatientGetReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SensorPatients []*v1.SensorPatient_Read `protobuf:"bytes,1,rep,name=sensor_patients,json=sensorPatients,proto3" json:"sensor_patients,omitempty"`
}

func (x *SensorPatientGetReply) Reset() {
	*x = SensorPatientGetReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_sensor_patient_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SensorPatientGetReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorPatientGetReply) ProtoMessage() {}

func (x *SensorPatientGetReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_sensor_patient_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorPatientGetReply.ProtoReflect.Descriptor instead.
func (*SensorPatientGetReply) Descriptor() ([]byte, []int) {
	return file_services_v1_sensor_patient_proto_rawDescGZIP(), []int{3}
}

func (x *SensorPatientGetReply) GetSensorPatients() []*v1.SensorPatient_Read {
	if x != nil {
		return x.SensorPatients
	}
	return nil
}

// =====================
// SensorPatientRetrieve
// =====================
type SensorPatientRetrieveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SensorId  string `protobuf:"bytes,1,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
	PatientId string `protobuf:"bytes,2,opt,name=patient_id,json=patientId,proto3" json:"patient_id,omitempty"`
}

func (x *SensorPatientRetrieveRequest) Reset() {
	*x = SensorPatientRetrieveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_sensor_patient_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SensorPatientRetrieveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorPatientRetrieveRequest) ProtoMessage() {}

func (x *SensorPatientRetrieveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_sensor_patient_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorPatientRetrieveRequest.ProtoReflect.Descriptor instead.
func (*SensorPatientRetrieveRequest) Descriptor() ([]byte, []int) {
	return file_services_v1_sensor_patient_proto_rawDescGZIP(), []int{4}
}

func (x *SensorPatientRetrieveRequest) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

func (x *SensorPatientRetrieveRequest) GetPatientId() string {
	if x != nil {
		return x.PatientId
	}
	return ""
}

type SensorPatientRetrieveReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SensorPatient *v1.SensorPatient_Read `protobuf:"bytes,1,opt,name=sensor_patient,json=sensorPatient,proto3" json:"sensor_patient,omitempty"`
}

func (x *SensorPatientRetrieveReply) Reset() {
	*x = SensorPatientRetrieveReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_services_v1_sensor_patient_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SensorPatientRetrieveReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SensorPatientRetrieveReply) ProtoMessage() {}

func (x *SensorPatientRetrieveReply) ProtoReflect() protoreflect.Message {
	mi := &file_services_v1_sensor_patient_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SensorPatientRetrieveReply.ProtoReflect.Descriptor instead.
func (*SensorPatientRetrieveReply) Descriptor() ([]byte, []int) {
	return file_services_v1_sensor_patient_proto_rawDescGZIP(), []int{5}
}

func (x *SensorPatientRetrieveReply) GetSensorPatient() *v1.SensorPatient_Read {
	if x != nil {
		return x.SensorPatient
	}
	return nil
}

var File_services_v1_sensor_patient_proto protoreflect.FileDescriptor

var file_services_v1_sensor_patient_proto_rawDesc = []byte{
	0x0a, 0x20, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x0b, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x1a,
	0x1e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x73, 0x65, 0x6e, 0x73, 0x6f,
	0x72, 0x5f, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x58, 0x0a, 0x1a, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09,
	0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x49, 0x64, 0x22, 0x60, 0x0a, 0x18, 0x53, 0x65, 0x6e,
	0x73, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x44, 0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f,
	0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x0d, 0x73, 0x65,
	0x6e, 0x73, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x22, 0x36, 0x0a, 0x17, 0x53,
	0x65, 0x6e, 0x73, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x73, 0x6f,
	0x72, 0x49, 0x64, 0x22, 0x5f, 0x0a, 0x15, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x50, 0x61, 0x74,
	0x69, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x46, 0x0a, 0x0f,
	0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x18,
	0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76,
	0x31, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x2e,
	0x52, 0x65, 0x61, 0x64, 0x52, 0x0e, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x69,
	0x65, 0x6e, 0x74, 0x73, 0x22, 0x5a, 0x0a, 0x1c, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x50, 0x61,
	0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x49,
	0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x64,
	0x22, 0x62, 0x0a, 0x1a, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e,
	0x74, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x44,
	0x0a, 0x0e, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x70, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74,
	0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x0d, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x50, 0x61, 0x74,
	0x69, 0x65, 0x6e, 0x74, 0x32, 0xc8, 0x02, 0x0a, 0x14, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x50,
	0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x65, 0x0a,
	0x13, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x12, 0x27, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e,
	0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x73,
	0x6f, 0x72, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x5c, 0x0a, 0x10, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x50, 0x61,
	0x74, 0x69, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x12, 0x24, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x50, 0x61, 0x74,
	0x69, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x22,
	0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e,
	0x73, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x47, 0x65, 0x74, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x12, 0x6b, 0x0a, 0x15, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x69,
	0x65, 0x6e, 0x74, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x12, 0x29, 0x2e, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72,
	0x50, 0x61, 0x74, 0x69, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x50, 0x61, 0x74, 0x69, 0x65,
	0x6e, 0x74, 0x52, 0x65, 0x74, 0x72, 0x69, 0x65, 0x76, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x42,
	0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x4d, 0x65,
	0x64, 0x69, 0x53, 0x74, 0x61, 0x74, 0x54, 0x65, 0x63, 0x68, 0x2f, 0x62, 0x69, 0x6f, 0x6d, 0x65,
	0x74, 0x72, 0x69, 0x63, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x62, 0x2f, 0x67,
	0x6f, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_services_v1_sensor_patient_proto_rawDescOnce sync.Once
	file_services_v1_sensor_patient_proto_rawDescData = file_services_v1_sensor_patient_proto_rawDesc
)

func file_services_v1_sensor_patient_proto_rawDescGZIP() []byte {
	file_services_v1_sensor_patient_proto_rawDescOnce.Do(func() {
		file_services_v1_sensor_patient_proto_rawDescData = protoimpl.X.CompressGZIP(file_services_v1_sensor_patient_proto_rawDescData)
	})
	return file_services_v1_sensor_patient_proto_rawDescData
}

var file_services_v1_sensor_patient_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_services_v1_sensor_patient_proto_goTypes = []interface{}{
	(*SensorPatientCreateRequest)(nil),   // 0: services.v1.SensorPatientCreateRequest
	(*SensorPatientCreateReply)(nil),     // 1: services.v1.SensorPatientCreateReply
	(*SensorPatientGetRequest)(nil),      // 2: services.v1.SensorPatientGetRequest
	(*SensorPatientGetReply)(nil),        // 3: services.v1.SensorPatientGetReply
	(*SensorPatientRetrieveRequest)(nil), // 4: services.v1.SensorPatientRetrieveRequest
	(*SensorPatientRetrieveReply)(nil),   // 5: services.v1.SensorPatientRetrieveReply
	(*v1.SensorPatient_Read)(nil),        // 6: models.v1.SensorPatient.Read
}
var file_services_v1_sensor_patient_proto_depIdxs = []int32{
	6, // 0: services.v1.SensorPatientCreateReply.sensor_patient:type_name -> models.v1.SensorPatient.Read
	6, // 1: services.v1.SensorPatientGetReply.sensor_patients:type_name -> models.v1.SensorPatient.Read
	6, // 2: services.v1.SensorPatientRetrieveReply.sensor_patient:type_name -> models.v1.SensorPatient.Read
	0, // 3: services.v1.SensorPatientService.SensorPatientCreate:input_type -> services.v1.SensorPatientCreateRequest
	2, // 4: services.v1.SensorPatientService.SensorPatientGet:input_type -> services.v1.SensorPatientGetRequest
	4, // 5: services.v1.SensorPatientService.SensorPatientRetrieve:input_type -> services.v1.SensorPatientRetrieveRequest
	1, // 6: services.v1.SensorPatientService.SensorPatientCreate:output_type -> services.v1.SensorPatientCreateReply
	3, // 7: services.v1.SensorPatientService.SensorPatientGet:output_type -> services.v1.SensorPatientGetReply
	5, // 8: services.v1.SensorPatientService.SensorPatientRetrieve:output_type -> services.v1.SensorPatientRetrieveReply
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_services_v1_sensor_patient_proto_init() }
func file_services_v1_sensor_patient_proto_init() {
	if File_services_v1_sensor_patient_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_services_v1_sensor_patient_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SensorPatientCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_sensor_patient_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SensorPatientCreateReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_sensor_patient_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SensorPatientGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_sensor_patient_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SensorPatientGetReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_sensor_patient_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SensorPatientRetrieveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_services_v1_sensor_patient_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SensorPatientRetrieveReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_services_v1_sensor_patient_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_services_v1_sensor_patient_proto_goTypes,
		DependencyIndexes: file_services_v1_sensor_patient_proto_depIdxs,
		MessageInfos:      file_services_v1_sensor_patient_proto_msgTypes,
	}.Build()
	File_services_v1_sensor_patient_proto = out.File
	file_services_v1_sensor_patient_proto_rawDesc = nil
	file_services_v1_sensor_patient_proto_goTypes = nil
	file_services_v1_sensor_patient_proto_depIdxs = nil
}
