// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        (unknown)
// source: models/v1/diseas_sensor.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DiseasSensor struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DiseasSensor) Reset() {
	*x = DiseasSensor{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_v1_diseas_sensor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiseasSensor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiseasSensor) ProtoMessage() {}

func (x *DiseasSensor) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_diseas_sensor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiseasSensor.ProtoReflect.Descriptor instead.
func (*DiseasSensor) Descriptor() ([]byte, []int) {
	return file_models_v1_diseas_sensor_proto_rawDescGZIP(), []int{0}
}

type DiseasSensor_Read struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiseasId string `protobuf:"bytes,1,opt,name=diseas_id,json=diseasId,proto3" json:"diseas_id,omitempty"`
	SensorId string `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
}

func (x *DiseasSensor_Read) Reset() {
	*x = DiseasSensor_Read{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_v1_diseas_sensor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiseasSensor_Read) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiseasSensor_Read) ProtoMessage() {}

func (x *DiseasSensor_Read) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_diseas_sensor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiseasSensor_Read.ProtoReflect.Descriptor instead.
func (*DiseasSensor_Read) Descriptor() ([]byte, []int) {
	return file_models_v1_diseas_sensor_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DiseasSensor_Read) GetDiseasId() string {
	if x != nil {
		return x.DiseasId
	}
	return ""
}

func (x *DiseasSensor_Read) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

type DiseasSensor_Create struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DiseasId string `protobuf:"bytes,1,opt,name=diseas_id,json=diseasId,proto3" json:"diseas_id,omitempty"`
	SensorId string `protobuf:"bytes,2,opt,name=sensor_id,json=sensorId,proto3" json:"sensor_id,omitempty"`
}

func (x *DiseasSensor_Create) Reset() {
	*x = DiseasSensor_Create{}
	if protoimpl.UnsafeEnabled {
		mi := &file_models_v1_diseas_sensor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiseasSensor_Create) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiseasSensor_Create) ProtoMessage() {}

func (x *DiseasSensor_Create) ProtoReflect() protoreflect.Message {
	mi := &file_models_v1_diseas_sensor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiseasSensor_Create.ProtoReflect.Descriptor instead.
func (*DiseasSensor_Create) Descriptor() ([]byte, []int) {
	return file_models_v1_diseas_sensor_proto_rawDescGZIP(), []int{0, 1}
}

func (x *DiseasSensor_Create) GetDiseasId() string {
	if x != nil {
		return x.DiseasId
	}
	return ""
}

func (x *DiseasSensor_Create) GetSensorId() string {
	if x != nil {
		return x.SensorId
	}
	return ""
}

var File_models_v1_diseas_sensor_proto protoreflect.FileDescriptor

var file_models_v1_diseas_sensor_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x69, 0x73, 0x65,
	0x61, 0x73, 0x5f, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x09, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2e, 0x76, 0x31, 0x22, 0x94, 0x01, 0x0a, 0x0c, 0x44,
	0x69, 0x73, 0x65, 0x61, 0x73, 0x53, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x1a, 0x40, 0x0a, 0x04, 0x52,
	0x65, 0x61, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x65, 0x61, 0x73, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x65, 0x61, 0x73, 0x49, 0x64,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x49, 0x64, 0x1a, 0x42, 0x0a,
	0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x64, 0x69, 0x73, 0x65, 0x61,
	0x73, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x69, 0x73, 0x65,
	0x61, 0x73, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x73, 0x6f, 0x72, 0x49,
	0x64, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x4d, 0x65, 0x64, 0x69, 0x53, 0x74, 0x61, 0x74, 0x54, 0x65, 0x63, 0x68, 0x2f, 0x62, 0x69, 0x6f,
	0x6d, 0x65, 0x74, 0x72, 0x69, 0x63, 0x2d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x62,
	0x2f, 0x67, 0x6f, 0x2f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x73, 0x2f, 0x76, 0x31, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_models_v1_diseas_sensor_proto_rawDescOnce sync.Once
	file_models_v1_diseas_sensor_proto_rawDescData = file_models_v1_diseas_sensor_proto_rawDesc
)

func file_models_v1_diseas_sensor_proto_rawDescGZIP() []byte {
	file_models_v1_diseas_sensor_proto_rawDescOnce.Do(func() {
		file_models_v1_diseas_sensor_proto_rawDescData = protoimpl.X.CompressGZIP(file_models_v1_diseas_sensor_proto_rawDescData)
	})
	return file_models_v1_diseas_sensor_proto_rawDescData
}

var file_models_v1_diseas_sensor_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_models_v1_diseas_sensor_proto_goTypes = []interface{}{
	(*DiseasSensor)(nil),        // 0: models.v1.DiseasSensor
	(*DiseasSensor_Read)(nil),   // 1: models.v1.DiseasSensor.Read
	(*DiseasSensor_Create)(nil), // 2: models.v1.DiseasSensor.Create
}
var file_models_v1_diseas_sensor_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_models_v1_diseas_sensor_proto_init() }
func file_models_v1_diseas_sensor_proto_init() {
	if File_models_v1_diseas_sensor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_models_v1_diseas_sensor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiseasSensor); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_v1_diseas_sensor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiseasSensor_Read); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_models_v1_diseas_sensor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiseasSensor_Create); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_models_v1_diseas_sensor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_models_v1_diseas_sensor_proto_goTypes,
		DependencyIndexes: file_models_v1_diseas_sensor_proto_depIdxs,
		MessageInfos:      file_models_v1_diseas_sensor_proto_msgTypes,
	}.Build()
	File_models_v1_diseas_sensor_proto = out.File
	file_models_v1_diseas_sensor_proto_rawDesc = nil
	file_models_v1_diseas_sensor_proto_goTypes = nil
	file_models_v1_diseas_sensor_proto_depIdxs = nil
}
