syntax = "proto3";

package services.v1;

option go_package = "github.com/MediStatTech/biometric-client/pb/go/services/v1";

import "models/v1/diseas.proto";

// =====================
// DiseasService
// =====================
service DiseasService {
  rpc DiseasCreate(DiseasCreateRequest) returns (DiseasCreateReply);
  rpc DiseasGet(DiseasGetRequest) returns (DiseasGetReply);
}


// =====================
// DiseasCreate
// =====================
message DiseasCreateRequest {
  models.v1.Diseas.Create diseas = 1;
}

message DiseasCreateReply {
    models.v1.Diseas.Read diseas = 1;
}

// =====================
// DiseasGet
// =====================
message DiseasGetRequest {
}

message DiseasGetReply {
    repeated models.v1.Diseas.Read diseases = 1;
}