syntax = "proto3";

package services.v1;

option go_package = "github.com/MediStatTech/biometric-client/pb/go/services/v1";

import "google/protobuf/timestamp.proto";

service PatientStatusService {
  rpc PatientStatusGetBatch(PatientStatusGetBatchRequest) returns (PatientStatusGetBatchReply);
  rpc PatientPanicTrigger(PatientPanicTriggerRequest)     returns (PatientPanicTriggerReply);
}

message PatientStatusGetBatchRequest {
  repeated string patient_ids = 1;
}

message PatientStatusGetBatchReply {
  repeated PatientStatus patient_statuses = 1;
}

message PatientStatus {
  string patient_id = 1;
  string status     = 2;
}

message PatientPanicTriggerRequest {
  string patient_id       = 1;
  int32  duration_seconds = 2;
}

message PatientPanicTriggerReply {
  google.protobuf.Timestamp panic_until = 1;
}
