syntax = "proto3";

package services.v1;

option go_package = "github.com/MediStatTech/biometric-client/pb/go/services/v1";

import "models/v1/sensor_patient_metric.proto";

service SensorPatientMetricService {
  rpc SensorPatientMetricGet(SensorPatientMetricGetRequest) returns (SensorPatientMetricGetReply);
}

message SensorPatientMetricGetRequest {
  string sensor_id  = 1;
  string patient_id = 2;
}

message SensorPatientMetricGetReply {
  repeated models.v1.SensorPatientMetric.Read measurements = 1;
}
